// <auto-generated />
namespace BYBY.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _1030 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1030));
        
        string IMigrationMetadata.Id
        {
            get { return "201710300752132_1030"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
