// <auto-generated />
namespace BYBY.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _201712047 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201712047));
        
        string IMigrationMetadata.Id
        {
            get { return "201712031326372_20171204-7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
