// <auto-generated />
namespace BYBY.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _1102 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1102));
        
        string IMigrationMetadata.Id
        {
            get { return "201711020710411_1102"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
