// <auto-generated />
namespace BYBY.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TBDateSetupAddHospitalId2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TBDateSetupAddHospitalId2));
        
        string IMigrationMetadata.Id
        {
            get { return "201801240512312_TBDateSetupAddHospitalId2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
